"""Add risk override to interview sessions

Revision ID: 0236fe769a6f
Revises: 0815c4559f37
Create Date: 2026-08-20 21:05:38.196105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0236fe769a6f'
down_revision: Union[str, Sequence[str], None] = '0815c4559f37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_sessions', sa.Column('risk_override', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_sessions', 'risk_override')
    # ### end Alembic commands ###
